services:
  triptrackbot:
    build: .
    container_name: triptrackbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - triptrack-net
      - proxy-net

networks:
  triptrack-net:
    name: triptrack-net
  proxy-net:
    external: true