from typing import Protocol
from app.models.car_settings import CarSettings
from app.models.trip import Trip


class TripRepository(Protocol):
    def save(self, trip: Trip) -> None: ...
    def get_all(self, user_id: int) -> list[Trip]: ...

class CarSettingsRepository(Protocol):
    def get(self, user_id: int) -> CarSettings | None: ...
    def save(self, settings: CarSettings) -> None: ...